import { baseApi } from "./baseApi";

// ─────────────────────────────────────────────────────────────────────────────
// Shared enums / unions
// ─────────────────────────────────────────────────────────────────────────────

export type TournamentFixtureStatus =
  | "DRAFT"
  | "SCHEDULED"
  | "MATCH_CREATED"
  | "LIVE"
  | "COMPLETED"
  | "CANCELLED";

export type TournamentFixtureSource = "MANUAL" | "AUTO";

export type TournamentMatchFilter = "ALL" | "LIVE" | "UPCOMING" | "PAST";

export type TournamentPitchType =
  | "ROUGH"
  | "CEMENT"
  | "TURF"
  | "ASTROTURF"
  | "MATTING"
  | "OTHER";

export type TournamentMatchType =
  | "LIMITED_OVERS"
  | "BOX_TURF"
  | "PAIR_CRICKET"
  | "TEST"
  | "THE_HUNDRED";

export type TournamentLineupMode = "FLEXIBLE" | "FIXED";

export type TournamentBallType = "TENNIS" | "LEATHER" | "OTHER";

export type TournamentFixtureActorType = "USER" | "SYSTEM";

// ─────────────────────────────────────────────────────────────────────────────
// Shared fixture structures
// ─────────────────────────────────────────────────────────────────────────────

export type TournamentFixtureVenue = {
  city: string;
  groundName?: string | null;
  pitchType?: TournamentPitchType | null;
  addressText?: string | null;
};

export type TournamentFixtureRules = {
  matchType: TournamentMatchType;
  oversLimit?: number | null;
  oversPerBowler?: number | null;
  lineupMode?: TournamentLineupMode | null;
  ballType?: TournamentBallType | null;
  wagonWheelEnabled?: boolean;
  shotSelectionEnabled?: boolean;
};

export type TournamentFixtureOfficials = {
  scorerUserIds?: string[];
  umpireNames?: string[];
  liveStreamerUserIds?: string[];
  otherNames?: string[];
};

export type TournamentFixtureTeamSnapshot = {
  teamId: string;
  name: string;
  shortName?: string | null;
  logoUrl?: string | null;
};

export type TournamentFixtureAuditActor = {
  actorType: TournamentFixtureActorType;
  actorId?: string | null;
};

// ─────────────────────────────────────────────────────────────────────────────
// Fixture response
// ─────────────────────────────────────────────────────────────────────────────

export type TournamentFixture = {
  id: string;
  tournamentId: string;
  roundId: string;

  groupId: string | null;
  matchId: string | null;

  teamAId: string;
  teamBId: string;

  teamASnapshot: TournamentFixtureTeamSnapshot;
  teamBSnapshot: TournamentFixtureTeamSnapshot;

  scheduledAt: string | null;
  timezone: string | null;

  sequenceNumber: number | null;
  roundMatchNumber: number | null;
  groupMatchNumber: number | null;

  venueSnapshot: TournamentFixtureVenue | null;
  matchRulesSnapshot: TournamentFixtureRules | null;
  officialsSnapshot: TournamentFixtureOfficials | null;

  status: TournamentFixtureStatus;
  createdFrom: TournamentFixtureSource;

  /**
   * The current API examples contain null for this property.
   * Replace unknown with an exact type after receiving a completed fixture.
   */
  resultMirror: unknown | null;

  cancellationReason: string | null;
  cancelledAt: string | null;

  createdBy: TournamentFixtureAuditActor | null;
  updatedBy: TournamentFixtureAuditActor | null;

  createdAt: string;
  updatedAt: string;
};

// ─────────────────────────────────────────────────────────────────────────────
// Manual fixture
// ─────────────────────────────────────────────────────────────────────────────

export type CreateManualFixtureBody = {
  roundId: string;
  groupId?: string;

  teamAId: string;
  teamBId: string;

  scheduledAt?: string;
  timezone?: string;

  sequenceNumber?: number;
  roundMatchNumber?: number;
  groupMatchNumber?: number;

  venue: TournamentFixtureVenue;
  rules: TournamentFixtureRules;
  officials?: TournamentFixtureOfficials;
};

export type CreateManualFixtureRequest = {
  tournamentId: string;
  body: CreateManualFixtureBody;
};

// ─────────────────────────────────────────────────────────────────────────────
// Auto-generate fixtures
// ─────────────────────────────────────────────────────────────────────────────

export type AutoGenerateFixturesBody = {
  roundId: string;

  /**
   * Send groupId only when generating fixtures for one group.
   */
  groupId?: string;

  /**
   * Send teamIds only when generating fixtures for selected teams.
   * Do not send both groupId and teamIds.
   */
  teamIds?: string[];

  repeatCount?: number;

  firstMatchDate: string;
  firstMatchTime: string;
  timezone?: string;

  intervalMinutes?: number;
  dailyMatchesPerGround?: number;

  venue: TournamentFixtureVenue;
  rules: TournamentFixtureRules;
  officials?: TournamentFixtureOfficials;
};

export type AutoGenerateFixturesRequest = {
  tournamentId: string;
  body: AutoGenerateFixturesBody;
};

export type AutoGeneratedFixture = {
  fixtureId: string;
  matchId: string;

  teamAId: string;
  teamBId: string;

  scheduledAt: string | null;
};

export type AutoGenerateFixturesResponse = {
  tournamentId: string;
  roundId: string;
  groupId: string | null;

  totalFixturesCreated: number;
  totalMatchesCreated: number;

  fixtures: AutoGeneratedFixture[];
};

// ─────────────────────────────────────────────────────────────────────────────
// Get fixtures
// ─────────────────────────────────────────────────────────────────────────────

export type GetTournamentFixturesQuery = {
  tournamentId: string;

  roundId?: string;
  groupId?: string;
  teamId?: string;

  status?: TournamentFixtureStatus;
  createdFrom?: TournamentFixtureSource;

  fromDate?: string;
  toDate?: string;

  skip?: number;
  limit?: number;
};

// The current API returns a direct array.
export type GetTournamentFixturesResponse = TournamentFixture[];

// ─────────────────────────────────────────────────────────────────────────────
// Fixture details
// ─────────────────────────────────────────────────────────────────────────────

export type GetFixtureDetailsRequest = {
  tournamentId: string;
  fixtureId: string;
};

// ─────────────────────────────────────────────────────────────────────────────
// Update fixture
// ─────────────────────────────────────────────────────────────────────────────

export type UpdateFixtureBody = Partial<{
  scheduledAt: string;
  timezone: string;

  sequenceNumber: number;
  roundMatchNumber: number;
  groupMatchNumber: number;

  venue: TournamentFixtureVenue;
  rules: TournamentFixtureRules;
  officials: TournamentFixtureOfficials;
}>;

export type UpdateFixtureRequest = {
  tournamentId: string;
  fixtureId: string;
  body: UpdateFixtureBody;
};

// ─────────────────────────────────────────────────────────────────────────────
// Cancel fixture
// ─────────────────────────────────────────────────────────────────────────────

export type CancelFixtureRequest = {
  tournamentId: string;
  fixtureId: string;

  body: {
    cancellationReason: string;
  };
};

// ─────────────────────────────────────────────────────────────────────────────
// Delete fixture
// ─────────────────────────────────────────────────────────────────────────────

export type DeleteFixtureRequest = {
  tournamentId: string;
  fixtureId: string;
};

export type DeleteFixtureResponse = {
  success?: boolean;
  message?: string;
};

// ─────────────────────────────────────────────────────────────────────────────
// API
// ─────────────────────────────────────────────────────────────────────────────

export const tournamentFixtureApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    // ─────────────────────────────────────────────────────────────────────────
    // Create manual fixture
    // ─────────────────────────────────────────────────────────────────────────

    createManualFixture: builder.mutation<
      TournamentFixture,
      CreateManualFixtureRequest
    >({
      query: ({ tournamentId, body }) => ({
        url: `/tournaments/${tournamentId}/fixtures/manual`,
        method: "POST",
        body,
      }),

      invalidatesTags: (_result, _error, { tournamentId }) => [
        {
          type: "Tournament",
          id: tournamentId,
        },
        {
          type: "TournamentFixture",
          id: tournamentId,
        },
      ],
    }),

    // ─────────────────────────────────────────────────────────────────────────
    // Auto-generate fixtures
    // ─────────────────────────────────────────────────────────────────────────

    autoGenerateFixtures: builder.mutation<
      AutoGenerateFixturesResponse,
      AutoGenerateFixturesRequest
    >({
      query: ({ tournamentId, body }) => ({
        url: `/tournaments/${tournamentId}/fixtures/auto-generate`,
        method: "POST",
        body,
      }),

      invalidatesTags: (_result, _error, { tournamentId }) => [
        {
          type: "Tournament",
          id: tournamentId,
        },
        {
          type: "TournamentFixture",
          id: tournamentId,
        },
      ],
    }),
    // ─────────────────────────────────────────────────────────────────────────
    // Preview Auto fixtures
    // ─────────────────────────────────────────────────────────────────────────

    previewAutoFixtures: builder.mutation<
      AutoGenerateFixturesResponse,
      AutoGenerateFixturesRequest
    >({
      query: ({ tournamentId, body }) => ({
        url: `/tournaments/${tournamentId}/fixtures/auto-generate/preview`,
        method: "POST",
        body,
      }),

      invalidatesTags: (_result, _error, { tournamentId }) => [
        {
          type: "Tournament",
          id: tournamentId,
        },
        {
          type: "TournamentFixture",
          id: tournamentId,
        },
      ],
    }),

    // ─────────────────────────────────────────────────────────────────────────
    // Get tournament fixtures
    // ─────────────────────────────────────────────────────────────────────────

    getTournamentFixtures: builder.query<
      GetTournamentFixturesResponse,
      GetTournamentFixturesQuery
    >({
      query: ({ tournamentId, ...params }) => ({
        url: `/tournaments/${tournamentId}/fixtures`,
        method: "GET",
        params,
      }),

      providesTags: (result, _error, { tournamentId }) => {
        if (!result) {
          return [
            {
              type: "TournamentFixture",
              id: tournamentId,
            },
          ];
        }

        return [
          {
            type: "TournamentFixture",
            id: tournamentId,
          },

          ...result.map((fixture) => ({
            type: "TournamentFixture" as const,
            id: fixture.id,
          })),
        ];
      },
    }),

    // ─────────────────────────────────────────────────────────────────────────
    // Get fixture details
    // ─────────────────────────────────────────────────────────────────────────

    getFixtureDetails: builder.query<
      TournamentFixture,
      GetFixtureDetailsRequest
    >({
      query: ({ tournamentId, fixtureId }) => ({
        url: `/tournaments/${tournamentId}/fixtures/${fixtureId}`,
        method: "GET",
      }),

      providesTags: (_result, _error, { fixtureId }) => [
        {
          type: "TournamentFixture",
          id: fixtureId,
        },
      ],
    }),

    // ─────────────────────────────────────────────────────────────────────────
    // Update fixture
    // ─────────────────────────────────────────────────────────────────────────

    updateFixture: builder.mutation<TournamentFixture, UpdateFixtureRequest>({
      query: ({ tournamentId, fixtureId, body }) => ({
        url: `/tournaments/${tournamentId}/fixtures/${fixtureId}`,
        method: "PATCH",
        body,
      }),

      invalidatesTags: (_result, _error, { tournamentId, fixtureId }) => [
        {
          type: "TournamentFixture",
          id: tournamentId,
        },
        {
          type: "TournamentFixture",
          id: fixtureId,
        },
      ],
    }),

    // ─────────────────────────────────────────────────────────────────────────
    // Cancel fixture
    // ─────────────────────────────────────────────────────────────────────────

    cancelFixture: builder.mutation<TournamentFixture, CancelFixtureRequest>({
      query: ({ tournamentId, fixtureId, body }) => ({
        url: `/tournaments/${tournamentId}/fixtures/${fixtureId}/cancel`,
        method: "POST",
        body,
      }),

      invalidatesTags: (_result, _error, { tournamentId, fixtureId }) => [
        {
          type: "TournamentFixture",
          id: tournamentId,
        },
        {
          type: "TournamentFixture",
          id: fixtureId,
        },
      ],
    }),

    // ─────────────────────────────────────────────────────────────────────────
    // Delete fixture
    // ─────────────────────────────────────────────────────────────────────────

    deleteFixture: builder.mutation<
      DeleteFixtureResponse,
      DeleteFixtureRequest
    >({
      query: ({ tournamentId, fixtureId }) => ({
        url: `/tournaments/${tournamentId}/fixtures/${fixtureId}`,
        method: "DELETE",
      }),

      invalidatesTags: (_result, _error, { tournamentId, fixtureId }) => [
        {
          type: "TournamentFixture",
          id: tournamentId,
        },
        {
          type: "TournamentFixture",
          id: fixtureId,
        },
      ],
    }),
  }),
});

// ─────────────────────────────────────────────────────────────────────────────
// Hooks
// ─────────────────────────────────────────────────────────────────────────────

export const {
  useCreateManualFixtureMutation,
  useAutoGenerateFixturesMutation,
  usePreviewAutoFixturesMutation,
  useGetTournamentFixturesQuery,
  useLazyGetTournamentFixturesQuery,
  useGetFixtureDetailsQuery,
  useLazyGetFixtureDetailsQuery,
  useUpdateFixtureMutation,
  useCancelFixtureMutation,
  useDeleteFixtureMutation,
} = tournamentFixtureApi;
